server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timefuze_architecture
    username: root
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE
