server:
  port: 9010

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:subscription_service
    username: sa
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE
